// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_r3wOoWbxtEQ9O3StufZvWZsaeb-MkmA',
    appId: '1:370727198859:web:70c8600deaff87f985748e',
    messagingSenderId: '370727198859',
    projectId: 'proiectlicenta-2971e',
    authDomain: 'proiectlicenta-2971e.firebaseapp.com',
    storageBucket: 'proiectlicenta-2971e.appspot.com',
    measurementId: 'G-2KKZRYVTWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfF4H85wIVR0p9mmaTdcrUkpnbjh4xLTs',
    appId: '1:370727198859:android:114e3400eb07687685748e',
    messagingSenderId: '370727198859',
    projectId: 'proiectlicenta-2971e',
    storageBucket: 'proiectlicenta-2971e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNIuveKi6nYlQeFZWW_L9QXgD86wXEMZ4',
    appId: '1:370727198859:ios:9f0c457c6c908fe385748e',
    messagingSenderId: '370727198859',
    projectId: 'proiectlicenta-2971e',
    storageBucket: 'proiectlicenta-2971e.appspot.com',
    iosClientId:
        '370727198859-snmgg8d62f5v75ri2vcnfibf6cl8f5e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvaplicatie1',
  );
}
